### PR TITLE
task-3

### PR DESCRIPTION
**Pull request by Deamon19**
BE urls added
Product mock response replaced with BE response

### CODE REVIEW

**Comment by AL1088717** [comment]
Hi @Deamon19, I cannot see any changes in project files except README.md. 
In this FE task your API paths should be updated with your actual API paths to your backend.
Application should get a single product and product list from backend (mocked data).

Please, use more descriptive commit messages, PR titles and descriptions. It would help everyone to better understand what was done.

**Comment by Deamon19** [comment]
> Hi @Deamon19, I cannot see any changes in project files except README.md. In this FE task your API paths should be updated with your actual API paths to your backend. Application should get a single product and product list from backend (mocked data).
> 
> Please, use more descriptive commit messages, PR titles and descriptions. It would help everyone to better understand what was done.

Didn't expect you to start reviewing so fast)
This was a test commit and PR, now everything is ready

**Comment by AL1088717** [comment]
No problem, take your time :)

**Comment by AL1088717** [comment]
@Deamon19

- `/products` request works well
- `/product/{productId}` request returns 403 CORS error on trying to manage product
image

**Comment by Deamon19** [comment]
> @Deamon19
> 
> * `/products` request works well
> * `/product/{productId}` request returns 403 CORS error on trying to manage product
>   image

In order to task 3.2 step 4
This endpoint is not needed to be integrated with Frontend right now.
Also evaluation criteria say only about /products endpoint

**Comment by AL1088717** [comment]
@Deamon19 

> Your own Frontend application is integrated with Product Service (/products API) and products from Product Service are represented on Frontend. AND POINT1 and POINT2 are done.

Your Product Service consists of 2 endpoints, both should be integrated with the FE app to  fulfil this criteria. That is meant by `/products API`, not just a single `/products` endpoint.

**Comment by Deamon19** [comment]
> @Deamon19
> 
> > Your own Frontend application is integrated with Product Service (/products API) and products from Product Service are represented on Frontend. AND POINT1 and POINT2 are done.
> 
> Your Product Service consists of 2 endpoints, both should be integrated with the FE app to fulfil this criteria. That is meant by `/products API`, not just a single `/products` endpoint.

Ok, it will take time to add one letter, but it seems strange and confusing to me that in 4-th subtasks of tasks 1 and 2 it is directly indicated which endpoint needs to be integrated with the frontend and which not. 
Now it's work for get by id endpoint as well.

**Pull request merged**
